
auth.token=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

defaults.org=rega-0p
defaults.project=react-native

defaults.url=https://sentry.io/
