export default {
  appName: 'רגע',
  intro1: 'חוקרים מסטנפורד הוכיחו שתרגול יומי של מדיטציה מוריד את לחץ הדם',
  favorites: '❤️ תרגולים שאהבתי',
  history: '📜 היסטוריית תרגולים',
  noSessions: 'לא נמצאו תרגולים',
  sessions: 'תרגולים',
  minutesSessions: 'דקות מדיטציה',
  welcomeTitle: 'היי, ברוכים הבאים לרגע',
  welcomeSubtitle: 'אפליקצית המיינדפולנס\nהראשונה בעברית',
  welcomeDescription:
    'עוד רגע ותוכלו להתחיל להתחבר לעצמכם\nלשפר את רמת הקשב והריכוז,\nלהירדם מהר יותר בלילה\nולהפחית לחצים וחרדות שמלווים\nאת כולנו בחיי היום-יום.',
  introSleep:
    'היי, ממש כיף שבאתם!\nעוד רגע ותוכלו להתחיל להתחבר לעצמכם, לשפר את רמת הקשב והריכוז,\nלהירדם מהר יותר בלילה ולהפחית לחצים וחרדות שמלווים את כולנו ביום-יום.',
  introStudy:
    "5 דק' ביום... זה כל הסיפור. מחקר שנערך לאחרונה בארה\"ב הראה כי ל-5 דק' מדיטציית מיינדפולנס יש השפעה מוכחת ומורגשת. אז השאלה אם רק 5 דקות ביום מספיקות? בהחלט כן! ",
  introRelax:
    'לנוח, להירגע, ולהירדם מ-ה-ר-!\n' +
    'בעזרת המיינדפולנס תוכלו להרגיע את הגוף והנפש, ולהירדם מהר ועמוק יותר. אם אתם מתקשים להירדם, ' +
    'עברו לאזור המתאים באפליקציה, נסו את התרגולים וראו בעצמכם. זה לא חלום, זו מציאות.',
  intro2:
    'במחקר שנערך מצאו שמדיטציה משפרת את יכולת הריכוז, המיקוד, תשומת הלב ויכולת לעבוד תחת לחץ.\nועוד רגע אחד אתם מתחילים!',
  chooseSex: 'בחר / בחרי\nבכדי שנוכל לפנות אליך\nולהתאים לך את התוכן',
  categorySelectorTitle:
    'להתחיל זה אחלה, אבל נשמח לדעת מאיפה,\nאז מה הכי מעניין אותך כרגע?',
  categorySelectionInfo:
    'בחירות אלו יעזרו לנו לכוון אותך. אין בבחירות הללו התחייבות והם לא ימנעו ממך לתוכן באפליקציה',
  sleepIntro: 'לישון טוב ולהירדם מהר',
  stressIntro: 'להתמודד טוב יותר עם חרדות',
  armyIntro: 'להתמודד עם השירות הצבאי',
  onTheRoadIntro: 'להעביר את הפקקים בכיף',
  southIntro: 'לשפר ביצועים מנטליים',
  studentsIntro: 'להוריד לחץ לפני מבחנים',
  next: 'הבא',
  meditation: 'מדיטציה',
  continue: 'המשך',
  expBeginner: 'מה זה מדיטציה?',
  expIntermediate: 'עשיתי קצת',
  expExpert: 'עשיתי הרבה',
  male: 'זכר',
  female: 'נקבה',
  home: 'בית',
  courses: 'קורסים',
  meditations: 'גלו עוד',
  profile: 'פרופיל',
  categories: 'נושאים',
  recommended: 'מומלץ עבורך',
  ourCourses: 'הקורסים שלנו',
  myWay: 'הדרך שלי',
  showAll: 'הצג הכל',
  details: 'פרטים',
  settings: 'הגדרות',
  aboutCourse: 'על הקורס',
  close: 'סגור',
  hours: 'שעות',
  minutes: "דק'",
  seconds: 'שניות',
  myMoments: 'הרגעים שלי',
  greeting: 'היי, אופיר',
  Greeting_general: 'במיוחד עבורך',
  personalized: 'מותאם אישית',
  latest_release: 'עלו לאחרונה',
  most_played: 'המושמעים ביותר',
  articles: 'רגע של קריאה',
  dailyStatus: 'השלמת את המדיטציה הראשונה שלך.\nכל הכבוד! :)',
  mentors: 'מנטורים',
  categoryCourses: 'קורסים בנושא ',
  categoryMeditations: 'תרגולים בודדים בנושא ',
  name: 'שם',
  sex: 'מין',
  email: 'דואל',
  password: 'סיסמה',
  verifyPassword: 'אישור סיסמה',
  signupTitle: 'הרשמה עם כתובת מייל',
  loginTitle: 'כניסה עם כתובת מייל',
  facebookTitle: 'או דרך פייסבוק',
  signup: 'הרשם',
  login: 'כניסה',
  logout: 'התנתק',
  facebook: 'Facebook',
  Cancel: 'לבטל',
  Delete: 'למחוק',
  // badges
  consecutiveWeekPracticed: 'סיימת שבוע רצוף',
  firstCourseCompleted: 'סיימת קורס ראשון',
  firstMeditation: 'סיימת מדיטציה ראשונה',
  categoryCompleted: 'סיימת קטגוריה',
  practiced50Min: 'סיימת 50 דקות של תירגול',
  practiced100Min: 'סיימת 100 דקות של תירגול',
  practiced150Min: 'סיימת 150 דקות של תירגול',
  practiced5Meditations: 'סיימת 5 מדיטציות',
  practiced15Meditations: 'סיימת 15 מדיטציות',
  practiced25Meditations: 'סיימת 25 מדיטציות',

  // subscribe
  subscribeTitle: 'רכישת מנוי',
  subscribeNowText: 'קנה מנוי וקבל גישה לכל התכנים ללא ההגבלה!',
  meditation_title: 'האם התנסית פעם במדיטציה?',

  // subscribe point

  point1: 'גישה ל150+ מדיטציות מודרכות בעברית שנבנו על ידי מומחים',
  point2: 'שפרו את איכות השינה והפחיתו חרדות ומתחים',
  point3: 'תוכן חדש ומגוון באפליקציה על בסיס שבוע',

  subscribeBottomText:
    'נסו את האפליקציה במשך 7 ימים בחינם! לאחר תקופה זו יתבצע חיוב אוטומטי בסך 159.90 שח עבור שנת שימוש באפליקציה.',

  subscribeBtn1: 'הירשמו ונסו חינם',
  point7: 'גישה חופשית למעל 50 מדיטציות מודרכות בעברית',
  heading1: 'היי , ברוכים הבאים לרגע',
  heading2: 'אפליקציית  המיינדפולנס',
  heading3: 'הראשונה בעברית',

  // background musics
};
